// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function helloWorld(param) {
  return "Hello Fabien";
}

var hi = "Hello Fabien";

function addOne(a) {
  return a + 1 | 0;
}

var myHuman2 = {
  name: "Asami",
  age: 37,
  sex: /* Female */0
};

function isFemale(entity) {
  var match = entity.sex;
  if (match) {
    return false;
  } else {
    return true;
  }
}

var myListA = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
};

var myListB = Pervasives.$at({
      hd: -1,
      tl: {
        hd: 0,
        tl: /* [] */0
      }
    }, {
      hd: 999,
      tl: /* [] */0
    });

var myListC = {
  hd: 1,
  tl: myListA
};

var $$double = List.map((function (i) {
        return (i << 1);
      }), myListA);

var max = List.fold_left((function (result, item) {
        if (item > result) {
          return item;
        } else {
          return result;
        }
      }), 0, myListA);

console.log(isFemale(myHuman2));

console.log("Hello Fabien, BuckleScript and Reason!");

console.log($$double);

console.log(max);

function makeCircle(xOpt, yOpt, radiusOpt, param) {
  var x = xOpt !== undefined ? xOpt : 0;
  var y = yOpt !== undefined ? yOpt : 0;
  var radius = radiusOpt !== undefined ? radiusOpt : 0;
  return x + Math.imul(y, radius) | 0;
}

var count = 43;

var x = [
  1,
  "ten"
];

var y = {
  hd: "Hello",
  tl: {
    hd: "World",
    tl: /* [] */0
  }
};

var myHuman = {
  name: "Fabien",
  age: 36,
  sex: /* Male */1
};

var myHuman3 = {
  name: "Elsa",
  age: 5,
  sex: /* Female */0
};

var nobody;

exports.count = count;
exports.helloWorld = helloWorld;
exports.hi = hi;
exports.addOne = addOne;
exports.x = x;
exports.y = y;
exports.myHuman = myHuman;
exports.myHuman2 = myHuman2;
exports.myHuman3 = myHuman3;
exports.isFemale = isFemale;
exports.myListA = myListA;
exports.myListB = myListB;
exports.myListC = myListC;
exports.$$double = $$double;
exports.max = max;
exports.nobody = nobody;
exports.makeCircle = makeCircle;
/* myListB Not a pure module */
